### ISSUE TITLE
Button state should reflect its state

### ISSUE THREAD

**Issue by OliverRhyme** [SimformSolutionsPvtLtd/SSJetPackComposeProgressButton#38]
**Describe the bug**
Button should stay at either `error` or `success` state unless the backing state is modified. It should not return on the idle state (ui-wise) automatically if the state does not reflect.

**To Reproduce**
1. Set the state to either `error` or `success`

**Expected behavior**
It should stay in its set state and not automatically go to idle even if it is just ui-wise.

**Smartphone (please complete the following information):**
- All

**Additional context**
This makes the library so opinionated and does not give the developer flexibility. It is also a common anti-pattern with declarative style ui to have a side-effect when state is changed. This kind of behavior also will not conform to single source of truth, and will cause the library to have unexpected behaviors.

**Comment by yashwantgowla-simform** [comment]
@OliverRhyme This issue requirement has been fixed in this PR [#50](https://github.com/SimformSolutionsPvtLtd/SSJetPackComposeProgressButton/pull/50). Please check and confirm when you get a chance.
