### ISSUE TITLE
Not able to use in material3

### ISSUE THREAD

**Issue by hiteshsarsava** [SimformSolutionsPvtLtd/SSJetPackComposeProgressButton#45]
**Describe the bug**
It's showing compile error, Please check the below error showing in android studio. It's for colors and elevation property :
```

@Composable
public fun SSJetPackComposeProgressButton(
    type: SSButtonType,
    width: Dp,
    height: Dp,
    onClick: () -> Unit,
    assetColor: Color,
    buttonState: SSButtonState,
    buttonBorderStroke: BorderStroke?,
    blinkingIcon: Boolean,
    cornerRadius: Int,
    speedMillis: Int,
    enabled: Boolean,
    elevation: [Error type: Unresolved type for androidx.compose.material.ButtonElevation]?,
    colors: [Error type: Unresolved type for androidx.compose.material.ButtonColors],
    padding: PaddingValues,
    alphaValue: Float,
    leftImagePainter: Painter?,
    rightImagePainter: Painter?,
    successIconPainter: Painter,
    failureIconPainter: Painter,
    successIconColor: Color,
    failureIconColor: Color,
    text: String?,
    textModifier: Modifier,
    fontSize: TextUnit,
    fontStyle: FontStyle?,
    fontFamily: FontFamily?,
    fontWeight: FontWeight?,
    hourHandColor: Color,
    customLoadingIconPainter: Painter,
    customLoadingEffect: SSCustomLoadingEffect,
    customLoadingPadding: Int
): Unit
```

More error details given by android studio

```
Cannot access class 'androidx.compose.material.ButtonColors'. Check your module classpath for missing or conflicting dependencies
Cannot access class 'androidx.compose.material.ButtonElevation'. Check your module classpath for missing or conflicting dependencies
```

**To Reproduce**
Cope paste the code from given in readme

**Expected behavior**
It should not give any compile time error.

**Screenshots**
![image](https://user-images.githubusercontent.com/16486943/209615566-166567c9-4027-4c87-9e09-ba1001eb09b2.png)

**Smartphone (please complete the following information):**
All Devices

**Additional context**
I am forking this lib and make it compatible to material3

Thanks for this awesome lib.

**Comment by ShwetaChauhan18** [comment]
@Purvesh-Dodiya: Please check this issue

**Comment by AdminQQZ** [comment]
![QQ_1721012459689](https://github.com/user-attachments/assets/6dee60ab-764c-489c-b603-a80c5d0b6cac)

how to make it work.

**Comment by hiteshsarsava** [comment]
Thanks. Solving this after 2 years. @AdminQQZ @yashwantgowla-simform

**Comment by yashwantgowla-simform** [comment]
@hiteshsarsava Apologies for the delay. We are going to release additional features going forward. Please stay tuned and help us with your feedbacks. Thank you!!
